# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7b24f296a099fe0531ad13e34b95f771e20a293124935b81e65a9eadf53ab6f7a4c1e7c7e603a3a611c978a0a9d23dec3b09e6f552751dcbe8312cf533854d8

test:
  secret_key_base: 148b9c67abe62185909beea1fa877e403abc600e249e31375ab5bf79d10925e9ca848cb2e1d055fd8101f29e8300d3b5b60aeedc66822117f09d597f66cafea2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
